name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # a cada 6h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Gera os arquivos (use v3)
      - uses: Platane/snk@v3
        with:
          github_user_name: lucasChicoski
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Publica os artefatos no branch "output"
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
